export LIBRARY_PATH=$LIBRARY_PATH:`pwd`/lib
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/lib
export LD_INCLUDE_PATH=$LD_INCLUDE_PATH:`pwd`/lib
export C_INCLUDE_PATH=$C_INCLUDE_PATH:`pwd`/include
export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:`pwd`/include
export INCLUDE_PATH=$INCLUDE_PATH:`pwd`/include
export PATH=$PATH:`pwd`/bin
export CC=$(which gcc)
export CXX=$(which g++)
