var searchData=
[
  ['sampler_6311',['Sampler',['../classvg_1_1Sampler.html',1,'vg']]],
  ['score_5ftraits_6312',['score_traits',['../structvg_1_1algorithms_1_1score__traits.html',1,'vg::algorithms']]],
  ['score_5ftraits_3c_20int_20_3e_6313',['score_traits&lt; int &gt;',['../structvg_1_1algorithms_1_1score__traits_3_01int_01_4.html',1,'vg::algorithms']]],
  ['score_5ftraits_3c_20traced_5fscore_5ft_20_3e_6314',['score_traits&lt; traced_score_t &gt;',['../structvg_1_1algorithms_1_1score__traits_3_01traced__score__t_01_4.html',1,'vg::algorithms']]],
  ['scoreproperties_6315',['ScoreProperties',['../structvg_1_1WFATree_1_1ScoreProperties.html',1,'vg::WFATree']]],
  ['scoreprovider_6316',['ScoreProvider',['../classhaplo_1_1ScoreProvider.html',1,'haplo']]],
  ['seed_6317',['Seed',['../structvg_1_1SnarlSeedClusterer_1_1Seed.html',1,'vg::SnarlSeedClusterer::Seed'],['../structvg_1_1NewSnarlSeedClusterer_1_1Seed.html',1,'vg::NewSnarlSeedClusterer::Seed']]],
  ['seed_5ftraits_6318',['seed_traits',['../structvg_1_1seed__traits.html',1,'vg']]],
  ['seed_5ftraits_3c_20newsnarlseedclusterer_3a_3aseed_20_3e_6319',['seed_traits&lt; NewSnarlSeedClusterer::Seed &gt;',['../structvg_1_1seed__traits_3_01NewSnarlSeedClusterer_1_1Seed_01_4.html',1,'vg']]],
  ['seed_5ftraits_3c_20snarlseedclusterer_3a_3aseed_20_3e_6320',['seed_traits&lt; SnarlSeedClusterer::Seed &gt;',['../structvg_1_1seed__traits_3_01SnarlSeedClusterer_1_1Seed_01_4.html',1,'vg']]],
  ['seqcomplexity_6321',['SeqComplexity',['../structvg_1_1SeqComplexity.html',1,'vg']]],
  ['serializable_6322',['Serializable',['../classhandlegraph_1_1Serializable.html',1,'handlegraph']]],
  ['serializablehandlegraph_6323',['SerializableHandleGraph',['../classhandlegraph_1_1SerializableHandleGraph.html',1,'handlegraph']]],
  ['shuffledpairs_6324',['ShuffledPairs',['../classvg_1_1ShuffledPairs.html',1,'vg']]],
  ['simpleconsistencycalculator_6325',['SimpleConsistencyCalculator',['../classvg_1_1SimpleConsistencyCalculator.html',1,'vg']]],
  ['simpletraversalsupportcalculator_6326',['SimpleTraversalSupportCalculator',['../classvg_1_1SimpleTraversalSupportCalculator.html',1,'vg']]],
  ['smallbitset_6327',['SmallBitset',['../classvg_1_1SmallBitset.html',1,'vg']]],
  ['smallsnarlsimplifier_6328',['SmallSnarlSimplifier',['../classvg_1_1SmallSnarlSimplifier.html',1,'vg']]],
  ['snarl_6329',['Snarl',['../structvg_1_1Snarl.html',1,'vg']]],
  ['snarl_5fless_6330',['snarl_less',['../structvg_1_1NestedCachedPackedTraversalSupportFinder_1_1snarl__less.html',1,'vg::NestedCachedPackedTraversalSupportFinder']]],
  ['snarlcaller_6331',['SnarlCaller',['../classvg_1_1SnarlCaller.html',1,'vg']]],
  ['snarldecomposition_6332',['SnarlDecomposition',['../classhandlegraph_1_1SnarlDecomposition.html',1,'handlegraph']]],
  ['snarlfinder_6333',['SnarlFinder',['../classvg_1_1SnarlFinder.html',1,'vg']]],
  ['snarlgraph_6334',['SnarlGraph',['../classvg_1_1SnarlGraph.html',1,'vg']]],
  ['snarlindex_6335',['SnarlIndex',['../classvg_1_1MinimumDistanceIndex_1_1SnarlIndex.html',1,'vg::MinimumDistanceIndex']]],
  ['snarlmanager_6336',['SnarlManager',['../classvg_1_1SnarlManager.html',1,'vg']]],
  ['snarlmindistance_6337',['SnarlMinDistance',['../classvg_1_1SnarlMinDistance.html',1,'vg']]],
  ['snarlorienteddistancemeasurer_6338',['SnarlOrientedDistanceMeasurer',['../classvg_1_1SnarlOrientedDistanceMeasurer.html',1,'vg']]],
  ['snarlrecord_6339',['SnarlRecord',['../structvg_1_1SnarlManager_1_1SnarlRecord.html',1,'vg::SnarlManager']]],
  ['snarlseedclusterer_6340',['SnarlSeedClusterer',['../classvg_1_1SnarlSeedClusterer.html',1,'vg']]],
  ['snarlstate_6341',['SnarlState',['../classvg_1_1SnarlState.html',1,'vg']]],
  ['snarltraversal_6342',['SnarlTraversal',['../structvg_1_1SnarlTraversal.html',1,'vg']]],
  ['snvvector_6343',['SNVvector',['../structhaplo_1_1linear__haplo__structure_1_1SNVvector.html',1,'haplo::linear_haplo_structure']]],
  ['sourcesinkoverlay_6344',['SourceSinkOverlay',['../classvg_1_1SourceSinkOverlay.html',1,'vg']]],
  ['sparseunionfind_6345',['SparseUnionFind',['../classvg_1_1SparseUnionFind.html',1,'vg']]],
  ['splicedhtsalignmentemitter_6346',['SplicedHTSAlignmentEmitter',['../classvg_1_1SplicedHTSAlignmentEmitter.html',1,'vg']]],
  ['spliceregion_6347',['SpliceRegion',['../classvg_1_1SpliceRegion.html',1,'vg']]],
  ['splicestats_6348',['SpliceStats',['../classvg_1_1SpliceStats.html',1,'vg']]],
  ['sswaligner_6349',['SSWAligner',['../classvg_1_1SSWAligner.html',1,'vg']]],
  ['stage_6350',['Stage',['../structvg_1_1Funnel_1_1Stage.html',1,'vg::Funnel']]],
  ['state_5fhash_6351',['state_hash',['../structvg_1_1state__hash.html',1,'vg']]],
  ['step_5fhandle_5ft_6352',['step_handle_t',['../structhandlegraph_1_1step__handle__t.html',1,'handlegraph']]],
  ['strandsplitgraph_6353',['StrandSplitGraph',['../classvg_1_1StrandSplitGraph.html',1,'vg']]],
  ['streaminbuf_6354',['streaminbuf',['../classvg_1_1io_1_1streaminbuf.html',1,'vg::io']]],
  ['streamindex_6355',['StreamIndex',['../classvg_1_1StreamIndex.html',1,'vg']]],
  ['streamindex_3c_20vg_3a_3aalgorithms_3a_3agraph_20_3e_6356',['StreamIndex&lt; vg::algorithms::Graph &gt;',['../classvg_1_1StreamIndex.html',1,'vg']]],
  ['streamindexbase_6357',['StreamIndexBase',['../classvg_1_1StreamIndexBase.html',1,'vg']]],
  ['streamistream_6358',['streamistream',['../classvg_1_1io_1_1streamistream.html',1,'vg::io']]],
  ['streammultiplexer_6359',['StreamMultiplexer',['../classvg_1_1io_1_1StreamMultiplexer.html',1,'vg::io']]],
  ['streamsorter_6360',['StreamSorter',['../classvg_1_1StreamSorter.html',1,'vg']]],
  ['string_5fhash_5fmap_6361',['string_hash_map',['../classvg_1_1string__hash__map.html',1,'vg']]],
  ['string_5fhash_5fset_6362',['string_hash_set',['../classvg_1_1string__hash__set.html',1,'vg']]],
  ['subcommand_6363',['Subcommand',['../classvg_1_1subcommand_1_1Subcommand.html',1,'vg::subcommand']]],
  ['subgraphoverlay_6364',['SubgraphOverlay',['../classvg_1_1SubgraphOverlay.html',1,'vg']]],
  ['subhandlegraph_6365',['SubHandleGraph',['../classhandlegraph_1_1algorithms_1_1SubHandleGraph.html',1,'handlegraph::algorithms::SubHandleGraph'],['../classvg_1_1SubHandleGraph.html',1,'vg::SubHandleGraph']]],
  ['subpath_6366',['Subpath',['../structvg_1_1Subpath.html',1,'vg']]],
  ['subpath_5ft_6367',['subpath_t',['../classvg_1_1subpath__t.html',1,'vg']]],
  ['support_6368',['Support',['../structvg_1_1Support.html',1,'vg']]],
  ['supportaugmentedgraph_6369',['SupportAugmentedGraph',['../structvg_1_1SupportAugmentedGraph.html',1,'vg']]],
  ['supportbasedsnarlcaller_6370',['SupportBasedSnarlCaller',['../classvg_1_1SupportBasedSnarlCaller.html',1,'vg']]],
  ['supportrestrictedtraversalfinder_6371',['SupportRestrictedTraversalFinder',['../classvg_1_1SupportRestrictedTraversalFinder.html',1,'vg']]],
  ['surjectingalignmentemitter_6372',['SurjectingAlignmentEmitter',['../classvg_1_1SurjectingAlignmentEmitter.html',1,'vg']]],
  ['surjector_6373',['Surjector',['../classvg_1_1Surjector.html',1,'vg']]],
  ['swaphaplotypescommand_6374',['SwapHaplotypesCommand',['../structvg_1_1SwapHaplotypesCommand.html',1,'vg']]]
];
