# Dockerfile for a full vg build from source
# (derived from vgteam/vg_docker)

FROM ubuntu:16.04
MAINTAINER vgteam
ARG vg_git_revision=master

# Make sure the en_US.UTF-8 locale exists, since we need it for tests
#RUN locale-gen en_US en_US.UTF-8 && DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales

# install apt dependencies
RUN apt-get -qq update && apt-get -qq install -y \
    pkg-config \
    sudo \
    curl \
    pv \
    wget \
    pigz \
    unzip \
    bsdmainutils \
    build-essential \
    make \
    automake \
    cmake \
    libtool \
    bison \
    flex \
    git \
    liblzma-dev \
    zlib1g-dev \
    libbz2-dev \
    liblz4-dev \
    libncurses5-dev \
    libgoogle-perftools-dev \
    libjansson-dev \
    librdf-dev \
    jq \
    bc \
    rs \
    redland-utils \
    raptor2-utils \
    rasqal-utils \
    samtools
ADD http://mirrors.kernel.org/ubuntu/pool/universe/b/bwa/bwa_0.7.15-2_amd64.deb /tmp/bwa.deb
RUN dpkg -i /tmp/bwa.deb

# copy over current directory to docker
ADD . /vg

# set our working directory
WORKDIR /vg

# Build
RUN . ./source_me.sh && make -j$(nproc) && make static

ENV PATH /vg/bin:$PATH
