#!/bin/bash
set -e

# Mine the Jenkins test log XML and the test output files and generate a report
# of how good VG is at various tasks.
# TODO: replace with a real implementation (maybe in Python).

usage() {
    # Print usage to stderr
    exec 1>&2
    printf "Usage: $0 XML_IN WORKDIR_IN HTML_OUT MD_OUT \n"
    exit 1
}

if [[ "$#" -ne 4 ]]; then
    # We need all the arguments
    usage
fi

# Gather all the arguments
XML_IN="${1}"; shift
WORKDIR_IN="${1}"; shift
HTML_OUT="${1}"; shift
MD_OUT="${1}"; shift

# Have a stub implementation
cat >"${HTML_OUT}" <<EOF
<!DOCTYPE html>
<html>
    <head>
        <title>Test Report</title>
    </head>
    <body>
        <h1>Test Report</h1>
EOF

XML_SIZE=$(stat --printf='%s' "${XML_IN}")
echo "<p>Tests created ${XML_SIZE} bytes of XML.</p>" >>"${HTML_OUT}"

cat >>"${HTML_OUT}" <<EOF
    </body>
</html>
EOF

echo "Generated HTML report ${HTML_OUT}"

# In the Markdown, "{{REPORT_URL}}" will be replaced with the URL to the uploaded HTML report.
cat >"${MD_OUT}" <<EOF
This is a summary of the performance of this commit or PR.

The full report is available [here]({{REPORT_URL}}).
EOF

echo "Generated Markdown summary ${MD_OUT}"


