#!/bin/bash

# Get the vg id
cd ~/vg && id=$(git log | head -1 | cut -f 2 -d\ | head -c 8) && cd -
echo testing vg-$id

# Generate 500k read pairs (1M reads) and their "true" positions from the vg graph:
echo generating simulated reads
time vg sim -s 271 -n 500000 -l 150 -p 500 -v 50 -x ~/pan/vg/index.xg -a | tee sim.gam | vg annotate -p -x ~/pan/vg/index.xg -a - | vg view -a - | jq -c -r '[ .name, .refpos[0].name, .refpos[0].offset ] | @tsv' | pv -l | sort >true.pos

# This can then be mapped six ways.

# By bwa:
# first split the file into the mates
vg view -a sim.gam | jq -cr 'select(.name | test("_1$"))' | pv -l | vg view -JaG - | vg view -X - | sed s/_1$// | gzip >sim_1.fq.gz
vg view -a sim.gam | jq -cr 'select(.name | test("_2$"))' | pv -l | vg view -JaG - | vg view -X - | sed s/_2$// | gzip >sim_2.fq.gz
# then map, correcting the names so they match vg's
echo bwa mem paired mapping
time bwa mem -t 32 ~/hs37d5/hs37d5.fa sim_1.fq.gz sim_2.fq.gz | grep -v ^@ | perl -ne '@val = split("\t", $_); print @val[0] . "_" . (@val[1] & 64 ? "1" : @val[1] & 128 ? "2" : "?"), "\t" . @val[2] . "\t" . @val[3] . "\t" . @val[4] . "\n";' | pv -l | sort >bwa_mem-pe.pos
join true.pos bwa_mem-pe.pos | ~/vg/scripts/pos_compare.py >bwa-pe.compare
# map single end
echo bwa mem single mapping
time bwa mem -t 32 ~/hs37d5/hs37d5.fa <(vg view -X sim.gam) | grep -v ^@ | pv -l | cut -f 1,3,4,5 | sort >bwa_mem-se.pos
join true.pos bwa_mem-se.pos | ~/vg/scripts/pos_compare.py >bwa-se.compare

# By vg-ref:
echo vg ref paired mapping
time vg map -iG sim.gam -x ~/ref/vg/index.xg -g ~/ref/vg/index.gcsa -t 32 | vg annotate -x ~/ref/vg/index.xg -p -a - | vg view -a - | pv -l | jq -c -r '[.name, .refpos[0].name, .refpos[0].offset, if .mapping_quality == null then 0 else .mapping_quality end ] | @tsv'  | sed s/null/0/g | sort >vg-ref-pe.pos
join true.pos vg-ref-pe.pos | ~/vg/scripts/pos_compare.py >vg-ref-pe.compare
echo vg ref single mapping
time vg map -G sim.gam -x ~/ref/vg/index.xg -g ~/ref/vg/index.gcsa -t 32 | vg annotate -x ~/ref/vg/index.xg -p -a - | vg view -a - | pv -l | jq -c -r '[.name, .refpos[0].name, .refpos[0].offset, if .mapping_quality == null then 0 else .mapping_quality end ] | @tsv'  | sed s/null/0/g | sort >vg-ref-se.pos
join true.pos vg-ref-se.pos | ~/vg/scripts/pos_compare.py >vg-ref-se.compare

# By vg-pan:
echo vg pan paired mappping
time vg map -iG sim.gam -x ~/pan/vg/index.xg -g ~/pan/vg/index.gcsa -t 32 | vg annotate -x ~/pan/vg/index.xg -p -a - | vg view -a - | pv -l | jq -c -r '[.name, .refpos[0].name, .refpos[0].offset, if .mapping_quality == null then 0 else .mapping_quality end ] | @tsv'  | sed s/null/0/g | sort >vg-pan-pe.pos
join true.pos vg-pan-pe.pos | ~/vg/scripts/pos_compare.py >vg-pan-pe.compare
echo vg pan single mappping
time vg map -G sim.gam -x ~/pan/vg/index.xg -g ~/pan/vg/index.gcsa -t 32 | vg annotate -x ~/pan/vg/index.xg -p -a - | vg view -a - | pv -l | jq -c -r '[.name, .refpos[0].name, .refpos[0].offset, if .mapping_quality == null then 0 else .mapping_quality end ] | @tsv'  | sed s/null/0/g | sort >vg-pan-se.pos
join true.pos vg-pan-se.pos | ~/vg/scripts/pos_compare.py >vg-pan-se.compare

# Now we combine the various positions into one table

echo combining results
( cat bwa-pe.compare    | awk 'BEGIN { OFS="\t"; print "correct", "mq", "aligner"; } { print $2, $3, "bwa.mem.pe" }' ;
  cat bwa-se.compare | awk 'BEGIN { OFS="\t"} { print $2, $3, "bwa.mem.se" }' ;
  cat vg-ref-pe.compare | awk 'BEGIN { OFS="\t"} { print $2, $3, "vg.ref.pe" }' ;
  cat vg-ref-se.compare | awk 'BEGIN { OFS="\t"} { print $2, $3, "vg.ref.se" }' ;
  cat vg-pan-pe.compare | awk 'BEGIN { OFS="\t"} { print $2, $3, "vg.pan.pe" }' ;
  cat vg-pan-se.compare | awk 'BEGIN { OFS="\t"} { print $2, $3, "vg.pan.se" }') >results-$id.tsv

# This can then be rendered using scripts in the vg repo
echo rendering ROC
~/vg/scripts/roc.R results-$id.tsv roc-$id.pdf
echo rendering QQ
~/vg/scripts/qq.R results-$id.tsv qq-$id.pdf
