#!/bin/zsh

name=$1
prefix=$2/$name
input=$3
xg=$4
gcsa=$5
mkdir -p $prefix
vg view -a $input | grep $name | vg view -JaG - >$prefix/no.gam
vg map -x $xg -g $gcsa -G $prefix/no.gam -a -t 1 -D 2>$prefix/err | vg view -a - | sed 's/"name": "/"name": "+/g' | vg view -JaG - >$prefix/try.gam
cat $prefix/no.gam $prefix/try.gam >$prefix/aln.gam
echo >>$prefix/err
echo "#####################################################" >>$prefix/err
echo "##### truth     #####################################" >>$prefix/err
echo "#####################################################" >>$prefix/err
vg view -a $prefix/no.gam >>$prefix/err
echo >>$prefix/err
echo "#####################################################" >>$prefix/err
echo "##### realigned #####################################" >>$prefix/err
echo "#####################################################" >>$prefix/err
vg view -a $prefix/try.gam >>$prefix/err
vg find -x z.xg -G $prefix/aln.gam | vg mod -i $prefix/aln.gam - | vg view -dp - | dot -Tpdf -o $prefix/incl.pdf
vg find -x z.xg -G $prefix/aln.gam | vg view -dA $prefix/aln.gam - | dot -Tpdf -o $prefix/aln.pdf
( echo "<style>h1 { font-size: 100px; } body { font-size: 50px }</style><h1>$name</h1>"; echo; echo '<pre>'; fold -w 160 -s $prefix/err; echo '</pre>' ) >$prefix/text.html
wkhtmltopdf --page-height 10in --page-width 40in $prefix/text.html $prefix/text.pdf 2>/dev/null
pdftk $prefix/text.pdf $prefix/aln.pdf $prefix/incl.pdf cat output $prefix/result.pdf
