#!/bin/bash

if [ $# -ne 6 ];
then
    echo "usage: "$(basename $0) "[graph.vg] [graph.xg] [chunk_size] [context] [output_pdf] [dot|neato]"
    echo "requires vg, pdfunite (from pdftk) and dot (graphviz)"
    echo "first index the graph with `vg index -x ...` and then choose a chunk size"
    exit
fi

vg=$1
xg=$2
chunk=$3
context=$4
out=$5
renderer=$6

h=$(vg view $vg | grep ^S | cut -f 2 | sort -n | head -1)
t=$(vg view $vg | grep ^S | cut -f 2 | sort -n | tail -1)

echo "generating pdfs"
for i in $(seq $h $chunk $t);
do
    s=$i
    e=$(echo $i + $chunk | bc)
    echo "generating pdf for $s to $e"
    vg find -x $xg -r $s:$e -c $context | vg view -dpn - | mars | $renderer -Tsvg -n -o $out.tmp.$s.svg
    cairosvg $out.tmp.$s.svg  -fpdf -o $out.tmp.$s.pdf
done

echo "combining pdfs"
pdfunite $(ls $out.tmp.$s.pdf | sort -V)

echo "cleaning up"
rm $out.tmp.*
