set(SRC  "/Users/zt-home/vg/deps/libdeflate/libdeflate.so")
set(DEST "/Users/zt-home/vg/build/lib/libdeflate.dylib")
if(EXISTS "${SRC}")
    file(COPY "${SRC}" DESTINATION "/Users/zt-home/vg/build/lib")
    if(APPLE)
        file(RENAME "/Users/zt-home/vg/build/lib/libdeflate.so" "${DEST}")
        execute_process(COMMAND install_name_tool -id "${DEST}" "${DEST}")
    endif()
endif()
