# Generated by cmake/deps_cmake_native.cmake
# Replicates: sed -i.bak '/yycleanup/d' raptor/build/src/turtle_lexer.c
set(LEXER_FILE "/Users/zt-home/vg/deps/raptor/build/src/turtle_lexer.c")
if(EXISTS ${LEXER_FILE})
    file(READ ${LEXER_FILE} _content)
    string(REGEX REPLACE "[^\n]*yycleanup[^\n]*\n" "" _patched "${_content}")
    file(WRITE ${LEXER_FILE} "${_patched}")
    message(STATUS "Patched raptor turtle_lexer.c (removed yycleanup)")
endif()
